### ISSUE TITLE
Can we send something to the server in the initial GET request?

### ISSUE THREAD

**Issue by Sjoerd82** [tserkov/vue-sse#10]
Is it possible to send something to the server on the first GET request to set up the connection? Ideally I'd add a user_id so the server only sends messages relevant to the connected user.

Is this (perhaps already) possible?

**Comment by tserkov** [comment]
You should be able to include it as a GET parameter in the URL you provide when setting up the connect, as shown below:

```javascript
let userID = 12345;

this.$sse(`/your-events-server?user_id=${userID}`)
```

**Comment by Sjoerd82** [comment]
That is indeed the way to go.
