### ISSUE TITLE
Add autoclose feature

### ISSUE THREAD

**Issue by sbernard31** [tserkov/vue-sse#13]
Regarding https://github.com/tserkov/vue-sse/issues/12#issuecomment-781834631, I see you are working on a v2.

There is some new feature I would like to see in it. **Tell me if it makes sense to you and if you need help.**

As a user, in my default usage I just want to be able to subscribe to events and change my vue when event is raised.
Most of the time, I don't want to thinking about re-connection or closing source.

So the idea would be to let vue-sse do it for me :
1. handle closing source on `beforeDestroy()`  (The most important part to me)
2. handle reconnection. (I'm not sure if this is needed)

For : 
1. [plugin mixing](https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin) could be used ([examples](https://www.digitalocean.com/community/tutorials/vuejs-creating-custom-plugins#your-first-plugin))
2. Reading #7 or [speficication](https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface), I'm not sure if this feature is really needed. But if reconnection is needed a default simple way would be good.

All of this would be the default behavior and could be deactivate to handle it manually.
(Optionally, we could imagine configuration do set the reconnection or automatic close behavior)

So finally the user code will just look something like this : 
```javascript
<template>
  <div>
    <p v-for="message in messages">{{ message }}</p>
  </div>
</template>

<script>
export default {
  name: 'sse-test',
  data() {
    return {
      messages: [],
    };
  },
  mounted() {
    this.$sse('/your-events-server', { format: 'json' }) // or { format: 'plain' }
      .then(sse => {
        // Catch any errors (ie. lost connections, etc.)
        sse.onError(e => {
          console.error('lost connection; giving up!', e);
        });

        // Listen for messages based on their event (in this case, "chat")
        sse.subscribe('chat', (message, rawEvent) => {
          this.messages.push(message);
        });
      })
      .catch(err => {
        // When this error is caught, it means the initial connection to the
        // events server failed.  No automatic attempts to reconnect will be made.
        console.error('Failed to connect to server', err);
      });
  },
};
</script>

```

**Comment by sbernard31** [comment]
(from https://github.com/tserkov/vue-sse/issues/12#issuecomment-790365258)
> it's a complicated thing to do. I will somehow need to associate an instance of SSEClient to a specific component.

My two cents idea was to add a Object field on the component instance which is a map eventSourceURL => EventSource.
We add the event source in this map only if autoCloseOnBeforeDestroy=true. (true could be the default value)
Then you add a mixing to your plugin which check this map entry and close each eventSource in the map.

**Comment by tserkov** [comment]
I attempted to implement this, but I discovered there's no way to associate an SSEClient with a Vue instance.

| Object | Vue Instance | SSEManager | SSEClient or URL |
| --- | --- | --- | --- |
| `Vue.mixin({ beforeCreate() {...}, beforeDestroy() {...} })` | ✅ | ✅ | ❌ |
| `Vue.prototype.$sse.create(...)` | ❌ | ✅ | ✅ |

I explored the following methods:
 - creating a `$sseClients` map on the instance during `beforeCreate`, but `$sse.create` can't access instance properties.
 - creating a `$clients` map on SSEManager with the SSEClient or URL as key, but `beforeDestroy` has no way of knowing if its instance contained that SSEClient or URL.

I don't think this is currently possible with how Vue/Javascript is designed. We would have to require users to pass a Vue instance (usually `this`) to `$sse.create` as an option, and I think that's dangerous business.

**Comment by sbernard31** [comment]
I guess there is maybe a solution : 

Instead of creating only 1 SSEManager, you can create 1 SSEManager by instance.
This way the SSEManager can hold all open clients. 

This will look like this : 
```Javascript
import SSEClient, { formatText } from './sse-client';

export function install(Vue, config) {
  // eslint-disable-next-line no-param-reassign, no-multi-assign
  // Vue.$sse = Vue.prototype.$sse = new SSEManager(config);

  Vue.mixin({
    beforeCreate() {
        this.$sse = new SSEManager(config); 
    },
    beforeDestroy () {
        Object.values(this.$sse.clients).forEach( client => client.disconnect());
    }
  })

  if (config && config.polyfill) {
    import('event-source-polyfill');
  }
}

export class SSEManager {
  constructor(config) {
    // this can be moved above to avoid to execute it each time we create an SSEManager
    this.$defaultConfig = Object.assign(
      {
        format: formatText,
        sendCredentials: false,
      },
      config,
    );
    this.clients = {};
  }

  create(config) {
    let cfg = Object.assign({}, this.$defaultConfig, config);
    let client = new SSEClient(cfg);
    if (cfg.autoclose){
        this.clients[cfg.url] = client; // maybe we don't need to use a map an array could be enough ?
    }
    return client;
  }
}

export default SSEManager;
```

This is just an idea and could probably be enhanced ? 
WDYT ?
The only problem I see is : 
 1.  we will create 1 SSEManager by vue instance. (I'm not able to know if this is an issue, I guess it could :confused: )
 2.  for each instance we will call beforeDestroy. (I guess most of the time list is empty so its not a big deal)
 
To resolved this I tried to add a useSSE:true data to my vue instance and change the code like this :
```Javascript
import SSEClient, { formatText } from './sse-client';

export function install(Vue, config) {
  // eslint-disable-next-line no-param-reassign, no-multi-assign
  // Vue.$sse = Vue.prototype.$sse = new SSEManager(config);

  Vue.mixin({
    // I need to change this from beforeCreate to created to be able to access to useSSE
    created() {
        if (this.useSSE)
             this.$sse = new SSEManager(config); 
    },
    beforeDestroy () {
        if (this.useSSE)
             Object.values(this.$sse.clients).forEach( client => client.disconnect());
    }
  })
  ... ... 
}
```
I guess it could works.
Do not hesitate to tell me what you think about all of this or if this bring to you new idea.
Maybe there is no good solution and so we just keep the manual disconnect() :disappointed:

**Comment by tserkov** [comment]
That's almost perfect, actually. I'll write down some pseudocode below before I start implementing:

```javascript
// component.vue
{
	data() { ... }
	sse: {
		cleanup: true
		// maybe allow other default options setting
	}
}
```

```javascript
// sse-manager.js
class SSEManager {
	// ...
	constructor() {
		// ...
		this._clients = nil; // nil means global instance
		// ...
	}
	// ...
	create(/* */) {
		const client = new SSEClient(...)

		if (this._clients !== nil) {
			// since _clients isn't nil, we should be tracking clients
			this.clients.push(client);
		}

		return client;
	}
	// ...
}

install() {
	// ...
	Vue.mixin({
		beforeCreate() {
			// checking $options is the real magic, as shown in component.vue
			if (this.$options.sse && this.$options.sse.cleanup) {
				this.$sse = new SSEManager() // create new manager to isolate references
				this.$sse._clients = []; // array means track clients
			}
		}

		beforeDestroy() {
			if (this.$sse._clients) {
				// since there's an array, we should close those clients
				for (let client in this.$sse._clients) {
					client.disconnect();
				}
			}
		}
	})
}
```

**Comment by tserkov** [comment]
Featured added in v2.2.0 (a9e55f0)!
