### ISSUE TITLE
Wrong Documentation

### ISSUE THREAD

**Issue by chumager** [tserkov/vue-sse#15]
Hi, I've been using your module for a while and all worked ok.

I saw you made breaking changes and when tried to apply the changes I realize your documentation is a mix between the old way and the new one. 

I guess now we have to use ```on("error", fn)``` instead of ```onError(fn)```, and after ```this.$sse.create``` we have to use ```await sse.connect```, and later ```sse.disconnect```.

Am I right? 

Your examples are all old, can you please update the documentation?

Regards.

**Comment by tserkov** [comment]
Fixed by @tgrk in #16
