### ISSUE TITLE
Documentation is out of date for v2

### ISSUE THREAD

**Issue by letianzhang** [tserkov/vue-sse#17]

**Comment by tserkov** [comment]
Hi there, @letianzhang!  I don't speak Chinese, so I'll trust that you throw what I'm typing into a translator just like I did for you -- the documention isn't completely updated from v1, and that's my fault. I'll keep this issue open to track my progress and keep me accountable.

Thanks.

**Comment by tserkov** [comment]
Docs updated in 12a28317e59d7cfbdaa83e833a93314bef596c27 for v2.1.1
