### ISSUE TITLE
Trying to get this to work with an existing Vue application and running into error

### ISSUE THREAD

**Issue by joshStillerman** [tserkov/vue-sse#2]
vue-sse.js?4318:49 Uncaught TypeError: source.onerror is not a function
    at EventSource.listener (vue-sse.js?4318:49)
listener @ vue-sse.js?4318:49

```
  mounted () {
    console.log('main mounted')
    this.$sse('http://localhost:8999/events', {format: 'json'})
    .then(sse => {
      sse.onError(e => {
        console.error('lost connection; giving up!', e)
      })
      sse.subscribe('', data => {
        console.warn('Received a message w/o an event!', data)
      })
      sse.subscribe('ss', (message) => {
        console.log('got one ' + message)
      })
      sse.onerror(e => {
        console.log('got an error ' + e)
      })
    })
    console.log('returning')
  },
```

**Comment by joshStillerman** [comment]
I also tried it without the sse.onerror(...) and got the same result

**Comment by tserkov** [comment]
Looks like this is actually a bug in [vue-sse.js#L49](https://github.com/tserkov/vue-sse/blob/b3c9fcb5022fb657a40941054d5f71b87caed2a7/src/vue-sse.js#L49) when a formatter errors and no error handler is set -- even though it looks like you're providing one with `sse.onError(...)` (there is no `sse.onerror()` method, by the way).  Give me a sec to push a patch and let me know if the following code works:
```javascript
  mounted () {
    console.log('main mounted')
    this.$sse('http://localhost:8999/events', {format: 'json'})
    .then(sse => {
      sse.onError(e => {
        console.error('lost connection or bad json returned; giving up!', e)
      })
      sse.subscribe('', data => {
        console.warn('Received a message w/o an event!', data)
      })
      sse.subscribe('ss', (message) => {
        console.log('got one ' + message)
      })
    })
    console.log('returning')
  },
```

**Comment by tserkov** [comment]
@joshStillerman 1.0.2 has been published, let me know if the code above works.  If it doesn't, could you provide me a sample repo with your issue? Thanks!

**Comment by joshStillerman** [comment]
Thanks -

   I already ripped it out, and just put in a call to EventSource.  I 
will test your new version on Monday.

THANKS !!!

-Josh
