### ISSUE TITLE
Feature: Vue 3 support

### ISSUE THREAD

**Issue by entermix** [tserkov/vue-sse#23]
When trying to install VueSSE with Vue 3, you may receive a warning:

> vue-sse@2.2.0" has incorrect peer dependency "vue@^2.0.0".

When trying to use according to the instructions, an error occurs:

> Uncaught TypeError: Vue.prototype is undefined

Are you planning to add support for Vue 3 (including the Composition API)? 

Thanks!

**Comment by JamesTann** [comment]
This issue was closed but I am seeing the same errors on install. Any updates?
