### ISSUE TITLE
Client initialization breaks when using forcePolyfill

### ISSUE THREAD

**Issue by taleeus** [tserkov/vue-sse#29]
Hi! I was trying to use the recent feature you added to specify custom headers forcing Polyfill  (#21) .
I am passing an Authorization header with a JWT. The code breaks constructing the `EventSourcePolyfill`:

```js
if (this.forcePolyfill) {
  this._source = eventsource.EventSourcePolyfill(
    this.url,
    Object.assign({}, this.config.polyfillOptions, {
      withCredentials: this.withCredentials,
    })
  );
}
```

The error is:
> TypeError: Cannot read properties of undefined (reading 'polyfillOptions')

It appears that `this.config` is undefined.
In the constructor, you are setting the properties extracting them from the config object, but you are not saving the config object itself:

```js
this.url = config.url;
this.withCredentials = !!config.withCredentials;
this.polyfillOptions = config.polyfillOptions || {};
this.forcePolyfill = !!config.forcePolyfill;
```

The fix should be easy: assigning `this.polyfillOptions` instead of `this.config.polyfillOptions`. I can do a pull request.

Thanks in advance!

**Comment by tserkov** [comment]
That'll teach me for pushing code without testing! Thanks for the quick identification and PR!
