### ISSUE TITLE
No matter what, event source returns error

### ISSUE THREAD

**Issue by piboistudios** [tserkov/vue-sse#3]
Hello,

I have been unable to get vue-sse to actually fetch the data. Which is strange, because when I check Data > XHR and Fetch in Chrome's DevTools, I can clearly see the data coming in, yet the only thing firing off is an error, and what's worse is the error is not descriptive at all. Anyways, here's my code:
```
// PortfolioLongDesc.vue
mounted() {
        (async () => {
            try {
                msgServer =  await this.$sse('longDesc', {format: 'plain'})
                .then(sse => {

                    sse.onError(e => {
                        console.log("Lost connection: ", e);
                 });
                 console.log("Subscribing to all events...");
                 sse.subscribe('', description => {
                     this.description = description;
                 });
                })

            } catch(err)
            {
                console.log("Failed to connect: ", err);
            }
        })();
```
On the server, I am simply intercepting the "/longDesc" path, setting the content-type to "text/event-stream" and sending back "data: My description" e.g.:
```
// server.js
if(pathname === "./longDesc")
    {
        result.setHeader("Content-type", "text/event-stream");
        result.end("data: " + middleware.getLongDesc());
        return;
    }
// middleware.js
const fs = require("fs");
module.exports = {
    getLongDesc: function (){
        rs = fs.readFileSync('./description.txt', 'utf8');
        return rs;
        
    }
}
```

As I said, the data seems to come in just fine, it just seems that vue-sse is registering the the event as an error, and never calling the subscription handler.

**Comment by tserkov** [comment]
Right away I spot two potential issues:
* You're using async/await, but also using Promise's `then`; you need one or the other;
* Your call on the `sse` is outside the `then`, so `sse` is `undefined`.

Try the following code:
```javascript
// PortfolioLongDesc.vue
mounted() {
	(async () => {
		try {
			msgServer = await this.$sse('longDesc', { format: 'plain' })

			msgServer.onError((err) => {
				console.log('Lost connection:', err);
			});

			console.log('Subscribing to all events...');
			msgServer.subscribe('', (description) => {
				this.description = description;
			});
		} catch (err) {
			console.log('Failed to connect:', err);
		}
	})();
}
```

Actually, I just realized the async/await example in the README is wrong (`sse` not defined, just `msgServer`) -- my bad! I'll get that fixed today, because that's the real issue here.

Remember kids -- don't pass Balmer's peak...

**Comment by piboistudios** [comment]
Haha, thanks! Keep me updated on the solution, this library is exactly what I am needing to use for my portfolio.

**Comment by tserkov** [comment]
I've updated the README, so that should be squared away now.

Did the code I provided above work for you?

**Comment by piboistudios** [comment]
I'll check it out in a bit. Will let you know

**Comment by piboistudios** [comment]
I don't think it's a problem with the library. I tried native EventSources and even those do not fire off onmessage. I'm not sure why this could be, considering I can literally see the data coming in via DevTools, and it matches the data I'm sending from the server.

**Comment by piboistudios** [comment]
Likely this is my problem 
![image](https://user-images.githubusercontent.com/21025122/39340428-bcf2327a-4993-11e8-8ec4-22e8d355c5f8.png)

**Comment by hellboy81** [comment]
Is last two `\n` important an the end?

The stream must then be parsed by reading everything line by line, with a U+000D CARRIAGE RETURN U+000A LINE FEED (CRLF) character pair, a single U+000A LINE FEED (LF) character, a single U+000D CARRIAGE RETURN (CR) character, and the end of the file being the four ways in which a line can end.

When a stream is parsed, a data buffer and an event name buffer must be associated with it. They must be initialized to the empty string

**Comment by tserkov** [comment]
[SSE W3C Spec, Section 6](https://www.w3.org/TR/2009/WD-eventsource-20090421/#parsing-an-event-stream) gives us the format, telling us `eof` is defined as a repeating `end-of-line`:
```
end-of-line   = ( cr lf / cr / lf / eof )
eof           = < matches repeatedly at the end of the stream >
```
as well as the preferred line ending character (`\n`) for web servers:
> Since connections established to remote servers for such resources are expected to be long-lived, UAs should ensure that appropriate buffering is used. **In particular, while line buffering with lines are defined to end with a single U+000A LINE FEED character is safe, block buffering or line buffering with different expected line endings can cause delays in event dispatch.**

All of which coincides with [SSE W3C Spec, Section 7](https://www.w3.org/TR/2009/WD-eventsource-20090421/#event-stream-interpretation) which tells us that blank lines end the transmitted event and it should be dispatched.
> If the line is empty (a blank line)
> Dispatch the event, as defined below.

A blank line is essentially leaving the current line (via `\n`) and then immediately leaving that line (again via `\n`) without putting anything on it. So, all together,  `\n\n`.

Technically, according to that spec, `\n\n\n\n\n` is a valid end-of-file marker.
