### ISSUE TITLE
Return type of SSEClient methods is wrong in Typescript interface - should not be void

### ISSUE THREAD

**Issue by davidzwa** [tserkov/vue-sse#33]
The typing states a void return type, which causes Typescript chaining with `.on(...).connect(...)` etc to fail:

https://github.com/tserkov/vue-sse/blob/7463952e5cffcaef7c6d03e1d472923906224a4d/types/index.d.ts#L40
`on(event: string, handler: MessageHandler): void;`
should be
`on(event: string, handler: MessageHandler): SSEClient;`

This goes for all methods: on, off and once

**Comment by tserkov** [comment]
Good catch! Thanks, fixed in v2.4.1!
