### ISSUE TITLE
Message Last-Event-Id missed

### ISSUE THREAD

**Issue by Waldmensch1** [tserkov/vue-sse#34]
I have a Server which expect sending an ack on each received event {type:'ack', id:'....'}. Therefore the Last-Event-Id of event is needed. How can I access it? The msg object only contains the payload itself

some docs about

https://kaazing.com/kaazing.io/doc/understanding-server-sent-events/

**Comment by tserkov** [comment]
Hi @Waldmensch1,

I've exposed Last-Event-Id to message handlers in v2.5.0, just released!

```javascript
sseClient.on('message', (data, lastEventId) => {
  console.log('data:', data);
  console.log('lastEventId': lastEventId);
});
```

Hope that helps!
