### ISSUE TITLE
Add option to define the HTTP method

### ISSUE THREAD

**Issue by rhuan080** [tserkov/vue-sse#36]
Hi,

According to [1], I didn`t see a way to define the HTTP method. I think it should provide a way to define it. Ex.:

```
sseClient = this.$sse.create({
      url: '/your-events-server',
      method: 'POST',
      format: 'json',
      withCredentials: true,
      polyfill: true,
    });
```
Let me know if it makes sense. If so, can I prepare a PR?

[1] - https://github.com/tserkov/vue-sse/blob/2e59e260d819d9493c953fa5ec2119cd1665b0b6/src/sse-client.js#L50

**Comment by tserkov** [comment]
Hi @rhuan080,

Unfortunately, the native event source doesn't allow specifying the HTTP method, nor does the specification.

However, it looks like it has been discussed over at the polyfill (https://github.com/Yaffle/EventSource/issues/148). I believe if you were to submit a PR to that repo, making sure to keep the PR scoped to just this feature (unlike the PR you see in that issue, where the submitter went a little out of scope with his style changes), then you have a very good chance of adding that feature. Then it would be available in this plugin!

Good luck!

**Comment by rhuan080** [comment]
I`m sorry for my delay. 

@tserkov thank you!
