### ISSUE TITLE
Edge IE11

### ISSUE THREAD

**Issue by remcocats** [tserkov/vue-sse#4]
Hi,
I have a problem when I use this package in Vue in Edge and IE11 I get a blank screen and get a SCRIPT1002: Syntax error in the code under this part:
```javscript
/***/ "./node_modules/vue-sse/src/vue-sse.js":
/*!*********************************************!*\
  !*** ./node_modules/vue-sse/src/vue-sse.js ***!
  \*********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var eventsource_polyfill__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! eventsource-polyfill */ \"./node_modules/even
```
I have set this as babel.config.js
```javscript
[
			'@babel/preset-env',
			{
				'targets': {
					'chrome': '58',
					'ie': '11'
				}
			}
		]
```

**Comment by mvanduijker** [comment]
You need a polyfill for IE and Edge. Try https://github.com/Yaffle/EventSource

**Comment by tserkov** [comment]
I'm using `babel-preset-es2015` for vue-sse, and honestly I'm not even sure which browsers that targets.  I need to update babel to use `@babel/preset-env` and be explicit with browser support.

**Comment by maloise44** [comment]
Hello,

any news about this issue ?

**Comment by remcocats** [comment]
Hi I dont use this project anymore
