### ISSUE TITLE
i need help,thanks

### ISSUE THREAD

**Issue by ayamzh** [tserkov/vue-sse#54]
![image](https://github.com/tserkov/vue-sse/assets/20828679/d4156157-826d-48de-987f-8322b78e8e5e)  

I want to create a progress bar using vue-sse. After initiating the request, each time it reaches the 10-second mark. It goes to the error branch.
![image](https://github.com/tserkov/vue-sse/assets/20828679/c86d2115-4e1f-49fb-9a24-290d17aa27ac)

**Comment by ayamzh** [comment]
the server side , is a  for-loop, never stop.

**Comment by tserkov** [comment]
Hi @ayamzh, this has actually come up before and is related to the polyfill, see https://github.com/tserkov/vue-sse/issues/35#issuecomment-986807802 for a workaround!
