### ISSUE TITLE
Error in mounted hook: "TypeError: this.$sse is not a function"

### ISSUE THREAD

**Issue by NKnuelle** [tserkov/vue-sse#8]
Hi,

I am trying to use this module with my Vue application. I registered the plugin in my main.js file:

    import VueSSE from 'vue-sse'

    Vue.config.productionTip = false

    new Vue({
      router,
      store,
      render: h => h(App)
    }).$mount('#app')

    Vue.use(Buefy, Vuex, axios, VueAxios, VueSSE)

And I try to use this in my component:

    mounted () {
      this.$sse('http://192.168.178.93:8000/api/get/statusupdate', { format: 'json' })
        .then(sse => {
          msgServer = sse

          sse.onError(e => {
            console.error('Connection lost', e)
          })
          sse.subscribe('', data => {
            console.warn('Received a message w/o an event!', data)
          })
        })
      },

But in my console I get this error:

    [Vue warn]: Error in mounted hook: "TypeError: this.$sse is not a function"

    found in

    ---> <RecordForm> at src/components/RecordForm.vue
       <BaseLayout> at src/components/BaseLayout.vue
         <Index> at src/views/Index.vue
           <App> at src/App.vue
             <Root>

I don't know what the problem is...

If I log this.$sse I get "undefined" which seems to be part of the problem.

**Comment by johnwoo-nl** [comment]
You're creating your Vue app and mounting it before applying the Vue plugins.
Try placing the `Vue.use(...)` line before the `new Vue(...).$mount` part.
